-- HockeyHub Database Schema
create extension if not exists "uuid-ossp";
create table if not exists players ( id bigint primary key, first_name text not null, last_name text not null, full_name text generated always as (first_name || ' ' || last_name) stored, position_code text not null, shoots_catches text, sweater_number int, height_inches int, weight_lbs int, birth_date date, birth_city text, birth_country text, current_team_id bigint, current_team_abbrev text, headshot_url text, is_active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now() );
create table if not exists teams ( id bigint primary key, franchise_id bigint, abbrev text not null unique, full_name text not null, common_name text, conference text, division text, logo_url text, primary_color text, secondary_color text, created_at timestamptz default now() );
create table if not exists contracts ( id uuid primary key default uuid_generate_v4(), player_id bigint references players(id), team_abbrev text not null, contract_type text not null, aav bigint not null, total_value bigint, start_year int not null, end_year int not null, no_trade_clause boolean default false, no_movement_clause boolean default false, expiry_status text, source text default 'manual', created_at timestamptz default now(), updated_at timestamptz default now() );
create table if not exists lineups ( id uuid primary key default uuid_generate_v4(), user_id uuid, name text not null, team_abbrev text not null, lineup_data jsonb not null, total_cap_hit bigint, is_public boolean default false, share_slug text unique, created_at timestamptz default now(), updated_at timestamptz default now() );
create table if not exists mock_trades ( id uuid primary key default uuid_generate_v4(), user_id uuid, name text, trade_data jsonb not null, is_legal boolean default true, is_public boolean default false, share_slug text unique, view_count int default 0, created_at timestamptz default now() );
alter table players enable row level security;
create policy "Players are public" on players for select using (true);
alter table teams enable row level security;
create policy "Teams are public" on teams for select using (true);
alter table contracts enable row level security;
create policy "Contracts are public" on contracts for select using (true);
alter table lineups enable row level security;
create policy "Insert lineups" on lineups for insert with check (true);
alter table mock_trades enable row level security;
create policy "Insert trades" on mock_trades for insert with check (true);
insert into teams (id, abbrev, full_name, common_name, conference, division, primary_color, secondary_color) values (24,'ANA','Anaheim Ducks','Ducks','Western','Pacific','#F47A38','#B9975B'),(6,'BOS','Boston Bruins','Bruins','Eastern','Atlantic','#FFB81C','#000000'),(7,'BUF','Buffalo Sabres','Sabres','Eastern','Atlantic','#003087','#FCB514'),(20,'CGY','Calgary Flames','Flames','Western','Pacific','#C8102E','#F1BE48'),(12,'CAR','Carolina Hurricanes','Hurricanes','Eastern','Metropolitan','#CC0000','#000000'),(16,'CHI','Chicago Blackhawks','Blackhawks','Western','Central','#CF0A2C','#000000'),(21,'COL','Colorado Avalanche','Avalanche','Western','Central','#6F263D','#236192'),(29,'CBJ(','Columbus Blue Jackets','Blue Jackets','Eastern','Metropolitan','#002654','#CE1126'),(25,'DAL','Dallas Stars','Stars','Western','Central','#006847','#8F8F8C'),(17,'DET','Detroit Red Wings','Red Wings','Eastern','Atlantic','#CE1126','#FFFFFF'),(22,'EDM','Edmonton Oilers','Oilers','Western','Pacific','#FF4C00','#003831'),(13,'FLA','Florida Panthers','Panthers','Eastern','Atlantic','#041E42','#C8102E'),(26,'LAK','Los Angeles Kings','Kings','Western','Pacific','#111111','#A2AAAD'),(30,'MIN','Minnesota Wild','Wild','Western','Central','#154734','#A6192E'),(8,'MTL','Montréal Canadiens','Canadiens','Eastern','Atlantic','#AF1E2D','#192168'),(18,'NSH','Nashville Predators','Predators','Western','Central','#FFB81C','#041E42'),(1,'NJD','New Jersey Devils','Devils','Eastern','Metropolitan','#CE1126','#000000'),(2,'NYI','New York Islanders','Islanders','Eastern','Metropolitan','#00539B','#F47D30'),(3,'NYR','New York Rangers','Rangers','Eastern','Metropolitan','#0038A8','#CE1126'),(9,'OTT','Ottawa Senators','Senators','Eastern','Atlantic','#C52032','#C69214'),(4,'PHI','Philadelphia Flyers','Flyers','Eastern','Metropolitan','#F74902','#000000'),(5,'PIT','Pittsburgh Penguins','Penguins','Eastern','Metropolitan','#FCB514','#000000'),(28,'SJS','San Jose Sharks','Sharks','Western','Pacific','#006D75','#EA7200'),(55,'SEA','Seattle Kraken','Kraken','Western','Pacific','#001628','#99D9D9'),(19,'STL','St. Louis Blues','Blues','Western','Central','#002F87','#FCB514'),(14,'TBL','Tampa Bay Lightning','Lightning','Eastern','Atlantic','#002868','#FFFFFF'),(10,'TOR','Toronto Maple Leafs','Maple Leafs','Eastern','Atlantic','#003E7E','#FFFFFF'),(59,'UTA','Utah Hockey Club','Hockey Club','Western','Central','#6CAEDF','#FFFFFF'),(23,'VAN','Vancouver Canucks','Canucks','Western','Pacific','#00205B','#00843D'),(54,'VGK','Vegas Golden Knights','Golden Knights','Western','Pacific','#B4975A','#333F42'),(15,'WSH','Washington Capitals','Capitals','Eastern','Metropolitan','#041E42','#C8102E'),(52,'WPG','Winnipeg Jets','Jets','Western','Central','#041E42','#004C97') on conflict (id) do nothing;
